services:

  firefox:
    image: selenium/standalone-firefox:4.16.1-20231219
    container_name: firefox
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - selenium-data:/home/seluser/Downloads
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=3600
      - SE_NODE_SESSION_TIMEOUT=3600
      - SE_VNC_PASSWORD=1234
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true 
      - SE_NODE_MAX_SESSIONS=5
    deploy:
      resources:
        limits:
          cpus: '0.4'

  django_fastapi:
    build: .
    pull_policy: build
    environment:
      - POSTGRES_HOST=psql_db
      - SELENIUM_DRIVER=firefox
      - REDIS_HOST=redis_db
    env_file:
      - ./.env
    # container_name: django_fastapi
    depends_on:
      - psql_db
      - redis_db
      # - celery_worker
      - firefox
    logging:
      driver: "json-file"
      options:
          max-size: "20m"
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    uvicorn project.asgi:app --host 0.0.0.0"
                    # python manage.py collectstatic --no-input &&
                    # python manage.py loaddata media/base_db.json &&
                    # python manage.py loaddata media/countries.json &&
                    # python manage.py create_periodic_task_for_delete_reviews &&
                    # python manage.py create_cities &&
                    # python manage.py create_moderator_group &&
                    # python manage.py periodic_task_for_parse_cash_courses &&
                    # python manage.py createsuperuser --no-input &&
                    # python manage.py parse_reviews_selenium &&

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
    ports:
      # - '81:80'
      - '80:80'
    depends_on:
      - django_fastapi
    logging:
      driver: "json-file"
      options:
          max-size: "20m"

  redis_db:
    image: redis:latest
    ports:
      - 6379:6379
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --replica-read-only no
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    restart: on-failure
    command: sh -c 'celery -A project worker -l info -c 20 -Ofair'
    environment:
      - POSTGRES_HOST=psql_db
      - SELENIUM_DRIVER=firefox
      - REDIS_HOST=redis_db
    env_file:
      - ./.env
    depends_on:
      - redis_db
      - psql_db
    logging:
      driver: "json-file"
      options:
          max-size: "20m"

  celery_beat:
    build: .
    restart: on-failure
    command: sh -c 'celery -A project beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler'
    environment:
      - POSTGRES_HOST=psql_db
      - REDIS_HOST=redis_db
    env_file:
      - ./.env
    depends_on:
      - redis_db
      - psql_db
      - celery_worker
    logging:
      driver: "json-file"
      options:
          max-size: "20m"

  psql_db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-size: "20m"

volumes:
  selenium-data:
  postgres-data:
  redis_data:
  static:
  media: