# Generated by Django 4.2.7 on 2024-01-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_alter_exchange_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название обменника(ru)')),
                ('en_name', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Название обменника(en)')),
                ('partner_link', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Партнёрская ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус обменника')),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='parnters_ex_name_5b89c2_idx'), models.Index(fields=['en_name'], name='parnters_ex_en_name_3a8191_idx')],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0)),
                ('fix_amount', models.FloatField(default=0)),
                ('cities', models.ManyToManyField(to='cash.city', verbose_name='Города')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_directions', to='cash.direction', verbose_name='Направление')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parnters.exchange', verbose_name='Обменник')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
    ]
