# Generated by Django 4.2.7 on 2024-01-24 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parnters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Модерация', 'Модерация'), ('Отклонён', 'Отклонён')], default='Модерация', help_text='При выборе статуса "Отклонён" попадает в очередь на удаление', max_length=20, verbose_name='Статус модерации')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию?')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='parnters.exchange', verbose_name='Наличный обменник')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-time_create', 'status', 'exchange'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Модерация', 'Модерация'), ('Отклонён', 'Отклонён')], default='Модерация', help_text='При выборе статуса "Отклонён" попадает в очередь на удаление', max_length=20, verbose_name='Статус модерации')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию?')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='parnters.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-time_create', 'status', 'review'),
            },
        ),
    ]
