# Generated by Django 4.2.7 on 2023-12-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='direction',
            index=models.Index(fields=['valute_from', 'valute_to'], name='no_cash_dir_valute__ec0d69_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangedirection',
            index=models.Index(fields=['valute_from', 'valute_to'], name='no_cash_exc_valute__d074f3_idx'),
        ),
    ]
