# Generated by Django 4.2.7 on 2024-01-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='exchange',
            name='no_cash_exc_name_63fecc_idx',
        ),
        migrations.RemoveIndex(
            model_name='exchange',
            name='no_cash_exc_en_name_063b1e_idx',
        ),
    ]
