# Generated by Django 4.2.7 on 2023-12-14 05:21

from django.db import migrations, models
import general_models.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='period_for_parse_black_list',
            field=models.IntegerField(blank=True, default=24, help_text='Рекомендуемое значение - 24 часа.\nЗначение - положительное целое число.При установлении в 0, останавливает задачу переодического парсинга чёрного списка', null=True, validators=[general_models.utils.model_validators.is_positive_validate], verbose_name='Частота парсинга чёрного списка в часах'),
        ),
    ]
