# Generated by Django 4.2.7 on 2024-02-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='actual_course',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Актуальный курс обмена'),
        ),
    ]
