# Generated by Django 4.2.7 on 2023-12-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['name'], name='cash_exchan_name_7ff575_idx'),
        ),
    ]
