# Generated by Django 4.2.7 on 2024-01-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='exchange',
            name='cash_exchan_name_7ff575_idx',
        ),
        migrations.RemoveIndex(
            model_name='exchange',
            name='cash_exchan_en_name_299154_idx',
        ),
    ]
