# Generated by Django 4.2.7 on 2024-01-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_exchange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['name'], 'verbose_name': 'Обменник', 'verbose_name_plural': 'Обменники'},
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['name'], name='cash_exchan_name_7ff575_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['en_name'], name='cash_exchan_en_name_299154_idx'),
        ),
    ]
