# Generated by Django 4.2.7 on 2024-03-14 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partners.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(auto_now=True, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Модерация', 'Модерация'), ('Отклонён', 'Отклонён')], default='Модерация', help_text='При выборе статуса "Отклонён" попадает в очередь на удаление', max_length=20, verbose_name='Статус модерации')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию?')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-time_create', 'status', 'review'),
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Администратор обменника',
                'verbose_name_plural': 'Администраторы обменников',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0, validators=[partners.utils.models.is_positive_validator], verbose_name='Процент')),
                ('fix_amount', models.FloatField(default=0, validators=[partners.utils.models.is_positive_validator], verbose_name='Фиксированная ставка')),
                ('time_update', models.DateTimeField(auto_now_add=True, help_text='Время указано по московскому часовому поясу. При не обновлении процентов или фикс. ставки в течении 3 дней, направление становится неактивным.', verbose_name='Последнее обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ('city__exchange', 'city', 'direction'),
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название обменника(ru)')),
                ('en_name', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Название обменника(en)')),
                ('partner_link', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Партнёрская ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус обменника')),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(auto_now=True, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Модерация', 'Модерация'), ('Отклонён', 'Отклонён')], default='Модерация', help_text='При выборе статуса "Отклонён" попадает в очередь на удаление', max_length=20, verbose_name='Статус модерации')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию?')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='partners.exchange', verbose_name='Наличный обменник')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-time_create', 'status', 'exchange'),
            },
        ),
        migrations.CreateModel(
            name='PartnerCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Есть ли доставка?')),
                ('has_office', models.BooleanField(default=False, verbose_name='Есть ли офис?')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_cities', to='cash.city', verbose_name='Город')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_cities', to='partners.exchange')),
            ],
            options={
                'verbose_name': 'Партнёрский город',
                'verbose_name_plural': 'Партнёрские города',
                'ordering': ('exchange', 'city'),
            },
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['name'], name='partners_ex_name_a1efdf_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['en_name'], name='partners_ex_en_name_29d294_idx'),
        ),
        migrations.AddField(
            model_name='direction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_directions', to='partners.partnercity', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='direction',
            name='direction',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('actual_course__isnull', False), ('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('actual_course__isnull', False), ('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='partner_directions', to='cash.direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='exchange',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='account', to='partners.exchange', verbose_name='Партнёрский обменник'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_superuser', False)), on_delete=django.db.models.deletion.CASCADE, related_name='moderator_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='partners.review', verbose_name='Отзыв'),
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together={('city', 'direction')},
        ),
    ]
