# Generated by Django 4.2.7 on 2024-02-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnercity',
            options={'verbose_name': 'Партнёрский город', 'verbose_name_plural': 'Партнёрские города'},
        ),
        migrations.AlterField(
            model_name='partnercity',
            name='has_delivery',
            field=models.BooleanField(default=False, verbose_name='Есть ли доставка?'),
        ),
        migrations.AlterField(
            model_name='partnercity',
            name='has_office',
            field=models.BooleanField(default=False, verbose_name='Есть ли офис?'),
        ),
    ]
