# Generated by Django 4.2.7 on 2024-03-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTimeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('unit_time', models.CharField(choices=[('SECOND', 'Секунды'), ('MINUTE', 'Минуты'), ('HOUR', 'Часы'), ('DAY', 'Дни')], max_length=100, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Управление временем партнёрских направлений',
                'verbose_name_plural': 'Управление временем партнёрских направлений',
            },
        ),
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название валюты(ru)')),
                ('en_name', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='Название валюты(en)')),
                ('code_name', models.CharField(max_length=10, unique=True, verbose_name='Кодовое сокращение')),
                ('type_valute', models.CharField(choices=[('Криптовалюта', 'Криптовалюта'), ('Эл. деньги', 'Эл. деньги'), ('Балансы криптобирж', 'Балансы криптобирж'), ('Банкинг', 'Банкинг'), ('Денежные переводы', 'Денежные переводы'), ('Наличные', 'Наличные')], max_length=30, verbose_name='Тип валюты')),
                ('icon_url', models.FileField(blank=True, null=True, upload_to='icons/valute/', verbose_name='Иконка валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code_name'],
                'indexes': [models.Index(fields=['code_name'], name='general_mod_code_na_79e396_idx')],
            },
        ),
    ]
