# Generated by Django 4.2.7 on 2024-01-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название валюты')),
                ('en_name', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='Название валюты(en)')),
                ('code_name', models.CharField(max_length=10, unique=True, verbose_name='Кодовое сокращение')),
                ('type_valute', models.CharField(choices=[('Криптовалюта', 'Криптовалюта'), ('Электронные деньги', 'Электронные деньги'), ('Балансы криптобирж', 'Балансы криптобирж'), ('Интернет-банкинг', 'Интернет-банкинг'), ('Денежные переводы', 'Денежные переводы'), ('Наличные', 'Наличные')], max_length=30, verbose_name='Тип валюты')),
                ('icon_url', models.FileField(blank=True, null=True, upload_to='icons/valute/', verbose_name='Иконка валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code_name'],
                'indexes': [models.Index(fields=['code_name'], name='general_mod_code_na_79e396_idx')],
            },
        ),
    ]
