# Generated by Django 4.2.7 on 2024-01-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valute',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название валюты(ru)'),
        ),
    ]
