# Generated by Django 4.2.7 on 2023-12-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='valute',
            index=models.Index(fields=['code_name'], name='general_mod_code_na_79e396_idx'),
        ),
    ]
