# Generated by Django 4.2.7 on 2024-02-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeupdate',
            name='unit_time',
            field=models.CharField(choices=[('SECOND', 'Секунды'), ('MINUTE', 'Минуты'), ('HOUR', 'Часы'), ('DAY', 'Дни')], max_length=100, verbose_name='Единица измерения'),
        ),
    ]
