# Generated by Django 4.2.7 on 2024-02-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0002_alter_timeupdate_unit_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeUpdate',
            new_name='PartnerTimeUpdate',
        ),
    ]
